The Care And Feeding Of Dragons -*- mode: org -*-

*** TODO Write Project Outline

* The Care And Feeding Of Dragons
** A Game Of Kobold Servitude
1. What sort of game?
   a. Clicker
   b. Idle
   c. Platform
   d. Cosy Farming Simulator
      You are a kobold.  You need to farm, fish, or otherwise get food for the dragon
      that shares your region.
2. Challenge
   Make sure you feed the dragon.  If it gets too hungry, you might
   start to look too tasty to resist.

* Exploring  The Options
** Clicker Game
*** Objective
  Keep The Dragon Fed
*** Game Mechanic
  Click on the screen
  Generate Food
  Feed the Dragon
  Use excess Food to get more help
  Eventually live a life of ease as the dragon is kept well fed
*** Win Condition
  Game Ends When You Want
*** Challenges
  Dragon Hunger Grows
  Too Well Fed means more dragons
  Natural Disasters
  Other Stuff

** Platform
*** Objective
  Keep the Dragon(s) fed.
*** Game Mechanic
  Jumping and climb to different platforms
  Collect food items
  Return them to the Dragon
*** Win Condition
  Dragon Fed Meter is full
*** Challenges
  Puzzle Solving
    Locked Areas
    Jumping Puzzles
  Enemies
    Try to stop you
    Steal food

** Cozy Farming
*** Objective
  Run A Farm.  Feed the Dragon
*** Game Mechanic
  Farm Fields
  Maximize your harvest
*** Win Condiiton
*** Challenges
